'use client';

import { useState } from 'react';

import SharedMonacoEditor from '../../components/SharedMonacoEditor';

export default function MonacoSharedPage() {
  const [editorValue, setEditorValue] = useState<string>('');

  const handlePrompt = () => {
    // Simulate LLM response by appending to the editor
    const currentValue = editorValue || '';
    const prompt = currentValue.trim();
    if (!prompt) return;

    // Add a separator and simulate LLM response
    const separator = '\n\n--- LLM Response ---\n';
    const llmResponse = `Based on your prompt: "${prompt}"\n\nThis is a simulated LLM response. In a real implementation, this would be generated by an AI model and appended to the shared editor. The editor maintains the full conversation history, allowing for continuous interaction between user prompts and AI responses.`;

    setEditorValue(currentValue + separator + llmResponse);
  };

  const clearEditor = () => {
    setEditorValue('');
  };

  return (
    <div
      style={{
        padding: '20px',
        fontFamily: 'system-ui',
        minHeight: '100vh',
        backgroundColor: '#f5f5f5',
      }}
    >
      <div
        style={{
          maxWidth: '1200px',
          margin: '0 auto',
          backgroundColor: 'white',
          borderRadius: '8px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
          overflow: 'hidden',
        }}
      >
        <div
          style={{
            padding: '20px',
            borderBottom: '1px solid #e1e5e9',
            backgroundColor: '#f8f9fa',
          }}
        >
          <h1 style={{ margin: 0, color: '#333' }}>Shared Monaco Editor</h1>
          <p style={{ margin: '5px 0 0 0', color: '#666' }}>
            One editor for prompts and LLM responses - conversation history
            maintained
          </p>
        </div>

        <div style={{ padding: '20px' }}>
          <div
            style={{
              display: 'flex',
              gap: '10px',
              marginBottom: '20px',
              flexWrap: 'wrap',
            }}
          >
            <button
              onClick={handlePrompt}
              style={{
                padding: '10px 20px',
                backgroundColor: '#007acc',
                color: 'white',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer',
                fontSize: '14px',
                fontWeight: '500',
              }}
              onMouseOver={e =>
                (e.currentTarget.style.backgroundColor = '#005aa3')
              }
              onMouseOut={e =>
                (e.currentTarget.style.backgroundColor = '#007acc')
              }
            >
              Generate Response
            </button>
            <button
              onClick={clearEditor}
              style={{
                padding: '10px 20px',
                backgroundColor: '#dc3545',
                color: 'white',
                border: 'none',
                borderRadius: '5px',
                cursor: 'pointer',
                fontSize: '14px',
                fontWeight: '500',
              }}
              onMouseOver={e =>
                (e.currentTarget.style.backgroundColor = '#c82333')
              }
              onMouseOut={e =>
                (e.currentTarget.style.backgroundColor = '#dc3545')
              }
            >
              Clear Editor
            </button>
          </div>

          <div
            style={{
              border: '1px solid #d1d5db',
              borderRadius: '6px',
              overflow: 'hidden',
            }}
          >
            <SharedMonacoEditor
              value={editorValue}
              onChange={value => setEditorValue(value || '')}
              language="plaintext"
              theme="vs-dark"
              height="600px"
              placeholder="Enter your prompt here... The LLM response will be appended below."
            />
          </div>

          <div
            style={{
              marginTop: '20px',
              padding: '15px',
              backgroundColor: '#f8f9fa',
              borderRadius: '6px',
              border: '1px solid #e1e5e9',
            }}
          >
            <h3 style={{ margin: '0 0 10px 0', color: '#333' }}>
              How it works:
            </h3>
            <ul style={{ margin: 0, paddingLeft: '20px', color: '#555' }}>
              <li>Type your prompt in the editor above</li>
              <li>Click "Generate Response" to simulate an LLM response</li>
              <li>
                The response is appended to the same editor, maintaining
                conversation history
              </li>
              <li>Use "Clear Editor" to start fresh</li>
              <li>
                Full Monaco Editor features: syntax highlighting, search, etc.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
